/*
SQLyog Enterprise Trial - MySQL GUI
MySQL - 8.0.16 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `product_datas` (
	`record_id` double ,
	`brand` varchar (765),
	`create_time` datetime ,
	`description` blob ,
	`image_url` varchar (765),
	`keyword` varchar (765),
	`material` varchar (765),
	`model` varchar (765),
	`product_name` varchar (765),
	`specification` varchar (765),
	`suitable_machine` varchar (765)
); 
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('2','小练制造','2019-05-30 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','超精密型数控机床','40Cr','XH1','121fd3445f','XL','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('3','小练制造','2019-06-14 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','超精密型数控机床','45号钢','XH3','125551535e','L','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('4','小练制造','2019-05-29 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','超精密型数控机床','40Cr','XH1','4a4f3c5344','XXL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('5','小练制造','2019-07-04 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012629634241.jpg','经济型数控机床','40Cr','XH3','be1g41gdd5','XXL','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('6','小练制造','2019-07-05 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012629634241.jpg','精密型数控机床','45号钢','XH1','g52e5d1b25','XXXL','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('7','小练制造','2019-07-05 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','经济型数控机床','45号钢','XH1','5cf53dd4dd','XL','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('8','小练制造','2019-06-12 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','精密型数控机床','45号钢','XH3','1fddc15cad','L','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('9','小练制造','2019-05-18 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','超精密型数控机床','40Cr','XH1','fe142b5333','M','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('10','小练制造','2019-06-03 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012629634241.jpg','经济型数控机床','45号钢','XH2','5b1e5dfgfc','M','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('11','小练制造','2019-05-30 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','超精密型数控机床','40Cr','XH1','3ccedg341a','L','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('12','小练制造','2019-06-14 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','精密型数控机床','40Cr','XH2','12d45ebe51','XXXL','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('13','小练制造','2019-06-30 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','精密型数控机床','40Cr','XH3','fed41gbfg5','L','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('14','小练制造','2019-06-15 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','超精密型数控机床','45号钢','XH1','aec4432bb5','XXL','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('15','小练制造','2019-06-03 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','精密型数控机床','40Cr','XH1','1bcfddcgcg','XL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('16','小练制造','2019-05-26 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','精密型数控机床','45号钢','XH1','fa5431ddac','XL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('17','小练制造','2019-06-20 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','超精密型数控机床','40Cr','XH1','1545555g3g','XXXL','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('18','小练制造','2019-06-11 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012630957211.jpg','超精密型数控机床','45号钢','XH1','4a2ge5c2ad','L','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('19','小练制造','2019-06-27 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','经济型数控机床','40Cr','XH1','421f4d3bac','M','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('20','小练制造','2019-05-25 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','精密型数控机床','40Cr','XH1','523cc5f221','XXL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('21','小练制造','2019-06-01 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','超精密型数控机床','40Cr','XH2','3b45ababg5','XXL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('22','小练制造','2019-07-02 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012630957211.jpg','精密型数控机床','45号钢','XH3','3ee1dbfdg5','M','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('23','小练制造','2019-06-02 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','超精密型数控机床','45号钢','XH3','ddf2c3a21b','M','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('24','小练制造','2019-07-05 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','精密型数控机床','40Cr','XH2','1d2fgee3bf','S','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('25','小练制造','2019-05-21 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','精密型数控机床','40Cr','XH2','3d42324dab','XXL','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('26','小练制造','2019-05-22 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','40Cr','XH2','dba1d11g12','L','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('27','小练制造','2019-05-31 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','超精密型数控机床','40Cr','XH2','ea31ecda2g','XXXL','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('28','小练制造','2019-06-12 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','经济型数控机床','45号钢','XH1','3g44ee42b4','XXL','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('29','小练制造','2019-06-29 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040853157045.jpg','经济型数控机床','45号钢','XH2','be2cb3abb1','XXXL','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('30','小练制造','2019-06-05 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','40Cr','XH1','g2e12eagb3','M','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('31','小练制造','2019-05-24 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','超精密型数控机床','40Cr','XH3','gd1c4c22da','XL','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('32','小练制造','2019-06-18 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','40Cr','XH2','c2fg32befg','XL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('33','小练制造','2019-06-07 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','超精密型数控机床','40Cr','XH1','21111ef2d2','S','刨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('34','小练制造','2019-05-18 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','超精密型数控机床','45号钢','XH3','e2db1f1gf2','XL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('35','小练制造','2019-06-05 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','经济型数控机床','45号钢','XH2','1dg2gb5aee','XL','车床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('36','小练制造','2019-06-29 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','超精密型数控机床','40Cr','XH3','cd41a3ed3e','XXXL','车床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('37','小练制造','2019-05-20 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','45号钢','XH2','adc2d45cg2','XXXL','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('38','小练制造','2019-05-26 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012630957211.jpg','经济型数控机床','40Cr','XH2','c535c14ge4','M','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('39','小练制造','2019-06-15 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012629634241.jpg','精密型数控机床','45号钢','XH1','42d4fe1ffc','XXXL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('40','小练制造','2019-06-07 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','超精密型数控机床','40Cr','XH1','g1bfge1ad2','S','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('41','小练制造','2019-05-20 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012629634241.jpg','超精密型数控机床','40Cr','XH3','2a25c5c42b','L','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('42','小练制造','2019-06-03 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','45号钢','XH3','db2afe21g1','XL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('43','小练制造','2019-07-04 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','超精密型数控机床','40Cr','XH1','4bfcgac53g','XXL','磨床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('44','小练制造','2019-06-04 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','精密型数控机床','40Cr','XH3','ea3gf4g21e','S','车床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('45','小练制造','2019-07-04 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012459940009.jpg','经济型数控机床','40Cr','XH2','cf53g2e53g','XL','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('46','小练制造','2019-05-21 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','经济型数控机床','45号钢','XH3','51cec3g14b','S','车床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('47','小练制造','2019-06-04 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040851769373.jpg','超精密型数控机床','45号钢','XH2','2edee3dfd4','M','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('48','小练制造','2019-06-23 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','40Cr','XH1','f3deegg35b','M','铣床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('49','小练制造','2019-07-05 16:00:59','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','精密型数控机床','45号钢','XH3','c2ebe4cbg5','XXXL','钻床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('50','小练制造','2019-06-02 22:58:11','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015040854204277.jpg','经济型数控机床','45号钢','XH2','34bbbafeg3','XXXL','车床');
insert into `product_datas` (`record_id`, `brand`, `create_time`, `description`, `image_url`, `keyword`, `material`, `model`, `product_name`, `specification`, `suitable_machine`) values('51','小练制造','2019-07-06 09:03:46','作为一个机械设计人员，在选材时必须了解工业发展趋势，按国家标准，结合我国资源和生产条件，从实际出发全面考虑材料及其选择机械制造中最常用的材料是钢和铸铁，其次是有色金属合金。非金属材料如塑料、橡胶等，在机械制造中也具有独特的使用价值。','http://www.hengdask.com/uploadfile/2015012640614057.jpg','经济型数控机床','40Cr','XH2','b342d5b3e5','L','钻床');
